import { createAccessControl } from "better-auth/plugins/access";
import {
	adminAc,
	defaultStatements,
	memberAc,
	ownerAc,
} from "better-auth/plugins/organization/access";

export const statement = {
	...defaultStatements,

	organization: ["update", "delete"],
	member: ["create", "update", "delete", "invite", "update_role", "remove"],
	onboarding: [
		"read",
		"create",
		"update",
		"archive",
		"start",
		"assign",
		"complete",
		"skip",
		"approve_document",
		"sign_acknowledgement",
	],

	employee: ["create", "read", "update", "terminate"],
	resignation: ["create", "read", "approve", "complete", "withdraw"],
	transfer: ["create", "read", "submit", "approve", "execute", "cancel"],

	payroll: ["create", "read", "update", "delete"],
	payslip: ["draft", "finalize", "reverse", "read"],
	payroll_period: ["create", "read", "finalize", "cancel", "delete"],
	advance: ["create", "read", "approve_hr", "approve_accounting", "disburse"],
	loan: [
		"create",
		"read",
		"approve_hr",
		"approve_accounting",
		"disburse",
		"write_off",
	],

	attendance: ["create", "read", "correct"],
	attendance_device: ["read", "manage", "sync"],
	attendance_punch: ["read", "process", "import"],
	geofence: ["read", "manage", "check_in"],
	attendance_exception: ["read", "resolve"],
	leave_request: ["create", "read", "approve", "reject", "cancel"],
	holiday: ["create", "read", "update", "archive"],
	work_location: ["read", "manage"],

	audit_log: ["read"],
	export: ["generate"],

	document: ["create", "read", "update", "archive", "scan_expiring"],

	journal: ["post", "reverse", "read"],
	account: ["create", "read", "update", "archive"],

	statutory_rules: ["read", "update"],

	posting: ["create", "read", "update", "publish", "archive"],
	applicant: ["create", "read", "update", "convert"],
	interview: ["create", "read", "update", "complete"],
	offer: ["create", "read", "extend", "withdraw"],

	appraisal: ["create", "read", "submit", "review", "finalize", "manage"],
	goal: ["create", "read", "update", "complete"],

	// "request" (Phase 12C) is the employee/manager self-service action for
	// asking HR for an asset. It is deliberately separate from "create" (which
	// mints an asset row) so self-service can be gated by an action staff
	// actually hold — see the offboarding documents.markUploaded dead-branch
	// lesson (a self-service handler must never sit behind a manage-only gate).
	asset: [
		"create",
		"read",
		"assign",
		"return",
		"write_off",
		"manage",
		"request",
	],

	ticket: ["create", "read", "update", "assign", "resolve", "close"],

	offboarding: [
		"create",
		"read",
		"update",
		"approve",
		"reject",
		"cancel",
		"start",
		"close",
		"complete_task",
		"manage_assets",
		"manage_access",
		"manage_documents",
		"manage_interview",
		"read_settlement",
	],
} as const;

export const ac = createAccessControl(statement);

// Biometric + Geofencing (Phase 11C) — the full managing grant for
// owner/admin/hr_admin. Spread into those role blocks.
const MANAGE_BIOMETRIC = {
	attendance_device: ["read", "manage", "sync"],
	attendance_punch: ["read", "process", "import"],
	geofence: ["read", "manage", "check_in"],
	attendance_exception: ["read", "resolve"],
} as const;

const FULL_OFFBOARDING = [
	"create",
	"read",
	"update",
	"approve",
	"reject",
	"cancel",
	"start",
	"close",
	"complete_task",
	"manage_assets",
	"manage_access",
	"manage_documents",
	"manage_interview",
	"read_settlement",
] as const;

export const tenant_owner = ac.newRole({
	...ownerAc.statements,
	member: ["create", "update", "delete", "invite", "update_role", "remove"],
	onboarding: [
		"read",
		"create",
		"update",
		"archive",
		"start",
		"assign",
		"complete",
		"skip",
		"approve_document",
		"sign_acknowledgement",
	],
	employee: ["create", "read", "update", "terminate"],
	resignation: ["create", "read", "approve", "complete", "withdraw"],
	transfer: ["create", "read", "submit", "approve", "execute", "cancel"],
	payroll: ["create", "read", "update", "delete"],
	payslip: ["draft", "finalize", "reverse", "read"],
	payroll_period: ["create", "read", "finalize", "cancel", "delete"],
	advance: ["create", "read", "approve_hr", "approve_accounting", "disburse"],
	loan: [
		"create",
		"read",
		"approve_hr",
		"approve_accounting",
		"disburse",
		"write_off",
	],
	attendance: ["create", "read", "correct"],
	leave_request: ["create", "read", "approve", "reject", "cancel"],
	holiday: ["create", "read", "update", "archive"],
	work_location: ["read", "manage"],
	audit_log: ["read"],
	export: ["generate"],
	document: ["create", "read", "update", "archive", "scan_expiring"],
	journal: ["post", "reverse", "read"],
	account: ["create", "read", "update", "archive"],
	statutory_rules: ["read", "update"],
	posting: ["create", "read", "update", "publish", "archive"],
	applicant: ["create", "read", "update", "convert"],
	interview: ["create", "read", "update", "complete"],
	offer: ["create", "read", "extend", "withdraw"],
	appraisal: ["create", "read", "submit", "review", "finalize", "manage"],
	goal: ["create", "read", "update", "complete"],
	asset: [
		"create",
		"read",
		"assign",
		"return",
		"write_off",
		"manage",
		"request",
	],
	ticket: ["create", "read", "update", "assign", "resolve", "close"],
	offboarding: FULL_OFFBOARDING,
	...MANAGE_BIOMETRIC,
});

export const tenant_admin = ac.newRole({
	...adminAc.statements,
	member: ["create", "update", "delete", "invite", "update_role", "remove"],
	onboarding: [
		"read",
		"create",
		"update",
		"archive",
		"start",
		"assign",
		"complete",
		"skip",
		"approve_document",
		"sign_acknowledgement",
	],
	employee: ["create", "read", "update", "terminate"],
	resignation: ["create", "read", "approve", "complete", "withdraw"],
	transfer: ["create", "read", "submit", "approve", "execute", "cancel"],
	payroll: ["create", "read", "update", "delete"],
	payslip: ["draft", "finalize", "reverse", "read"],
	payroll_period: ["create", "read", "finalize", "cancel", "delete"],
	advance: ["create", "read", "approve_hr", "approve_accounting", "disburse"],
	loan: [
		"create",
		"read",
		"approve_hr",
		"approve_accounting",
		"disburse",
		"write_off",
	],
	attendance: ["create", "read", "correct"],
	leave_request: ["create", "read", "approve", "reject", "cancel"],
	holiday: ["create", "read", "update", "archive"],
	work_location: ["read", "manage"],
	audit_log: ["read"],
	export: ["generate"],
	document: ["create", "read", "update", "archive", "scan_expiring"],
	journal: ["post", "reverse", "read"],
	account: ["create", "read", "update", "archive"],
	statutory_rules: ["read"],
	posting: ["create", "read", "update", "publish", "archive"],
	applicant: ["create", "read", "update", "convert"],
	interview: ["create", "read", "update", "complete"],
	offer: ["create", "read", "extend", "withdraw"],
	appraisal: ["create", "read", "submit", "review", "finalize", "manage"],
	goal: ["create", "read", "update", "complete"],
	asset: [
		"create",
		"read",
		"assign",
		"return",
		"write_off",
		"manage",
		"request",
	],
	ticket: ["create", "read", "update", "assign", "resolve", "close"],
	offboarding: FULL_OFFBOARDING,
	...MANAGE_BIOMETRIC,
});

export const hr_admin = ac.newRole({
	...adminAc.statements,
	member: ["create", "update", "delete", "invite", "update_role", "remove"],
	onboarding: [
		"read",
		"create",
		"update",
		"archive",
		"start",
		"assign",
		"complete",
		"skip",
		"approve_document",
		"sign_acknowledgement",
	],
	employee: ["create", "read", "update", "terminate"],
	resignation: ["create", "read", "approve", "complete", "withdraw"],
	transfer: ["create", "read", "submit", "approve", "execute", "cancel"],
	payroll: ["create", "read", "update"],
	payslip: ["draft", "read"],
	payroll_period: ["create", "read"],
	advance: ["create", "read", "approve_hr"],
	loan: ["create", "read", "approve_hr"],
	attendance: ["create", "read", "correct"],
	leave_request: ["create", "read", "approve", "reject", "cancel"],
	holiday: ["create", "read", "update", "archive"],
	work_location: ["read", "manage"],
	audit_log: ["read"],
	export: ["generate"],
	document: ["create", "read", "update", "archive", "scan_expiring"],
	journal: ["read"],
	account: ["read"],
	statutory_rules: ["read"],
	posting: ["create", "read", "update", "publish", "archive"],
	applicant: ["create", "read", "update", "convert"],
	interview: ["create", "read", "update", "complete"],
	offer: ["create", "read", "extend", "withdraw"],
	appraisal: ["create", "read", "review", "finalize", "manage"],
	goal: ["create", "read", "update"],
	asset: ["create", "read", "assign", "return", "manage", "request"],
	ticket: ["create", "read", "update", "assign", "resolve", "close"],
	offboarding: FULL_OFFBOARDING,
	...MANAGE_BIOMETRIC,
});

export const payroll_admin = ac.newRole({
	...memberAc.statements,
	employee: ["read"],
	resignation: ["read", "complete"],
	payroll: ["create", "read", "update", "delete"],
	payslip: ["draft", "finalize", "reverse", "read"],
	payroll_period: ["create", "read", "finalize", "cancel", "delete"],
	advance: ["read", "approve_accounting", "disburse"],
	loan: ["read", "approve_accounting", "disburse", "write_off"],
	attendance: ["read"],
	attendance_device: ["read"],
	attendance_punch: ["read"],
	geofence: ["read", "check_in"],
	attendance_exception: ["read"],
	leave_request: ["read"],
	holiday: ["read"],
	work_location: ["read"],
	audit_log: ["read"],
	export: ["generate"],
	document: ["read"],
	journal: ["post", "reverse", "read"],
	account: ["create", "read", "update", "archive"],
	statutory_rules: ["read"],
	posting: ["read"],
	applicant: ["read"],
	interview: ["read"],
	offer: ["read"],
	appraisal: ["read"],
	goal: ["read"],
	asset: ["read", "request"],
	ticket: ["read"],
	offboarding: ["read", "read_settlement"],
});

export const manager = ac.newRole({
	...memberAc.statements,
	employee: ["read"],
	resignation: ["read", "approve"],
	payslip: ["read"],
	payroll_period: ["read"],
	attendance: ["read"],
	attendance_device: ["read"],
	attendance_punch: ["read"],
	geofence: ["read", "check_in"],
	attendance_exception: ["read", "resolve"],
	leave_request: ["create", "read", "approve", "reject"],
	holiday: ["read"],
	work_location: ["read"],
	document: ["read"],
	asset: ["read", "request"],
	appraisal: ["read", "submit", "review"],
	goal: ["create", "read", "update"],
	posting: ["read"],
	applicant: ["read"],
	interview: ["read", "update", "complete"],
	onboarding: ["read", "complete", "skip", "assign"],
	ticket: ["create", "read"],
	offboarding: ["read", "approve", "complete_task"],
});

export const employee = ac.newRole({
	...memberAc.statements,
	employee: ["read"],
	resignation: ["create", "read", "withdraw"],
	onboarding: ["read", "complete", "sign_acknowledgement"],
	payslip: ["read"],
	payroll_period: ["read"],
	advance: ["create", "read"],
	loan: ["create", "read"],
	attendance: ["read"],
	geofence: ["read", "check_in"],
	leave_request: ["create", "read", "cancel"],
	holiday: ["read"],
	work_location: ["read"],
	document: ["create", "read"],
	asset: ["read", "request"],
	appraisal: ["read", "submit"],
	goal: ["create", "read", "update", "complete"],
	posting: ["read"],
	ticket: ["create", "read"],
});

export const auditor = ac.newRole({
	...memberAc.statements,
	employee: ["read"],
	resignation: ["read"],
	transfer: ["read"],
	onboarding: ["read"],
	payroll: ["read"],
	attendance_device: ["read"],
	attendance_punch: ["read"],
	geofence: ["read"],
	attendance_exception: ["read"],
	payslip: ["read"],
	payroll_period: ["read"],
	advance: ["read"],
	loan: ["read"],
	attendance: ["read"],
	leave_request: ["read"],
	holiday: ["read"],
	work_location: ["read"],
	audit_log: ["read"],
	export: ["generate"],
	document: ["read"],
	journal: ["read"],
	account: ["read"],
	statutory_rules: ["read"],
	posting: ["read"],
	applicant: ["read"],
	interview: ["read"],
	offer: ["read"],
	appraisal: ["read"],
	goal: ["read"],
	asset: ["read"],
	ticket: ["read"],
	offboarding: ["read", "read_settlement"],
});

export const recruiter = ac.newRole({
	...memberAc.statements,
	employee: ["read"],
	posting: ["create", "read", "update", "publish", "archive"],
	applicant: ["create", "read", "update", "convert"],
	interview: ["create", "read", "update", "complete"],
	offer: ["create", "read", "extend", "withdraw"],
	onboarding: ["read", "start"],
	document: ["read"],
	// Recruiters are staff too: they may self-request company property and see
	// their own custody (read), but not the asset inventory (canViewAssets=false).
	asset: ["read", "request"],
});

export const helpdesk_agent = ac.newRole({
	...memberAc.statements,
	employee: ["read"],
	ticket: ["create", "read", "update", "assign", "resolve", "close"],
	document: ["read"],
});

export const roles = {
	tenant_owner,
	tenant_admin,
	hr_admin,
	payroll_admin,
	manager,
	employee,
	auditor,
	recruiter,
	helpdesk_agent,
} as const;

export type TenantRole = keyof typeof roles;
