// biome-ignore-all lint: one-shot dry-run report generator (Phase 21B).
//
// Produces a Markdown (human) + JSON (machine) migration report. The report is
// PII-FREE by construction: it emits only counts, table/field names,
// classifications, and opaque IDs — never names, emails, salaries, or bank data.

import type { Classification, TableInspection } from "./types-v1";

export type TenantReadiness = {
	tenantId: string;
	name: string;
	counts: Record<string, number>;
	blockers: string[];
	ready: boolean;
};

export type DryRunResult = {
	generatedAt: string;
	v1Url: string; // redacted
	v2Staging: string | null;
	totals: Record<string, number>;
	tables: TableInspection[];
	tenants: TenantReadiness[];
	featureGaps: string[];
	statutoryReview: string[];
};

const CLASS_LABEL: Record<Classification, string> = {
	direct_map: "Direct map",
	transform_map: "Transform map",
	requires_new_v2_feature: "Requires new v2 feature",
	archive_only: "Archive only",
	ignore_defer: "Ignore / defer",
};

function countByStatus(t: TableInspection) {
	const c = { mapped: 0, manual_review: 0, unmapped: 0, dropped: 0 };
	for (const f of t.fields) {
		c[f.status]++;
	}
	return c;
}

export function toJson(r: DryRunResult): string {
	return JSON.stringify(r, null, 2);
}

export function toMarkdown(r: DryRunResult): string {
	const L: string[] = [];
	L.push("# v1 → v2 Migration Dry-Run Report");
	L.push("");
	L.push(`**Generated:** ${r.generatedAt}`);
	L.push(`**v1 source (read-only):** \`${r.v1Url}\``);
	L.push(
		`**v2 staging target:** ${r.v2Staging ? `\`${r.v2Staging}\`` : "_none configured (schema-from-code mode)_"}`
	);
	L.push("");
	L.push(
		"> DRY RUN — no rows were written to v1 or to any v2 database. This report"
	);
	L.push(
		"> classifies coverage only. Generated by `scripts/migration/run-dry-run.ts`."
	);
	L.push("");

	// --- totals ---
	L.push("## 1. Totals");
	L.push("");
	L.push("| Metric | Count |");
	L.push("| --- | ---: |");
	for (const [k, v] of Object.entries(r.totals)) {
		L.push(`| ${k} | ${v} |`);
	}
	L.push("");

	// --- coverage matrix ---
	L.push("## 2. Table coverage matrix");
	L.push("");
	L.push(
		"| v1 table | rows | classification | v2 target | mapped/review/unmapped/dropped |"
	);
	L.push("| --- | ---: | --- | --- | --- |");
	for (const t of [...r.tables].sort((a, b) => b.rowCount - a.rowCount)) {
		const c = countByStatus(t);
		const fieldSummary = t.fields.length
			? `${c.mapped}/${c.manual_review}/${c.unmapped}/${c.dropped}`
			: "—";
		L.push(
			`| ${t.v1Table} | ${t.rowCount} | ${CLASS_LABEL[t.classification]} | ${t.v2Target ?? "—"} | ${fieldSummary} |`
		);
	}
	L.push("");

	// --- fields needing attention ---
	L.push("## 3. Fields needing attention (manual_review + unmapped)");
	L.push("");
	let any = false;
	for (const t of r.tables) {
		const flagged = t.fields.filter(
			(f) => f.status === "manual_review" || f.status === "unmapped"
		);
		if (flagged.length === 0) {
			continue;
		}
		any = true;
		L.push(`### ${t.v1Table}`);
		for (const f of flagged) {
			L.push(
				`- \`${f.v1}\` → ${f.v2 ?? "**(no v2 home)**"} — _${f.status}_${f.note ? `: ${f.note}` : ""}`
			);
		}
		L.push("");
	}
	if (!any) {
		L.push("_None._");
		L.push("");
	}

	// --- unmappable records ---
	L.push("## 4. Records that cannot map (blocked)");
	L.push("");
	const blocked = r.tables.filter((t) => t.unmappable.length > 0);
	if (blocked.length === 0) {
		L.push(
			"_None — every inspected record has a destination (pending feature builds)._"
		);
	} else {
		for (const t of blocked) {
			L.push(
				`- **${t.v1Table}**: ${t.unmappable.length} record(s) — ${t.unmappable[0].reason}`
			);
		}
	}
	L.push("");

	// --- feature gaps ---
	L.push("## 5. Required v2 feature gaps (block write-migration)");
	L.push("");
	if (r.featureGaps.length === 0) {
		L.push("_None._");
	} else {
		for (const g of r.featureGaps) {
			L.push(`- ${g}`);
		}
	}
	L.push("");

	// --- statutory ---
	L.push("## 6. Payroll / statutory fields needing manual review");
	L.push("");
	if (r.statutoryReview.length === 0) {
		L.push("_None._");
	} else {
		for (const s of r.statutoryReview) {
			L.push(`- ${s}`);
		}
	}
	L.push("");

	// --- per-tenant readiness ---
	L.push("## 7. Per-tenant migration readiness");
	L.push("");
	for (const tn of r.tenants) {
		L.push(
			`### ${tn.name} (\`${tn.tenantId}\`) — ${tn.ready ? "✅ data maps (pending feature builds)" : "⚠ blocked"}`
		);
		const countStr = Object.entries(tn.counts)
			.map(([k, v]) => `${k}: ${v}`)
			.join(" · ");
		L.push(`- ${countStr}`);
		if (tn.blockers.length) {
			L.push("- Blockers:");
			for (const b of tn.blockers) {
				L.push(`  - ${b}`);
			}
		}
		L.push("");
	}

	L.push("---");
	L.push("");
	L.push(
		"_Next: Phase 21C — payroll/attendance reconciliation dry-run (recompute each v1"
	);
	L.push(
		"payslip in v2's engine and assert net-pay parity before any write-migration)._"
	);
	L.push("");
	return L.join("\n");
}
