import { relations } from "drizzle-orm";
import {
	boolean,
	date,
	index,
	integer,
	jsonb,
	numeric,
	pgEnum,
	pgTable,
	text,
	timestamp,
	unique,
} from "drizzle-orm/pg-core";

import { user } from "./auth";
import {
	contract,
	cuid,
	department,
	employeeProfile,
	orgRef,
	timestamps,
} from "./hr-core";

export const payrollRunStatusEnum = pgEnum("payroll_run_status", [
	"draft",
	"preview",
	"confirmed",
	"paid",
	"reversed",
]);

export const payslipStatusEnum = pgEnum("payslip_status", [
	"draft",
	"confirmed",
	"paid",
]);

export const payItemTypeEnum = pgEnum("pay_item_type", [
	"allowance",
	"deduction",
]);

export const payslipLineTypeEnum = pgEnum("payslip_line_type", [
	"earning",
	"deduction",
	"tax",
	"employer_contribution",
]);

export const loanTypeEnum = pgEnum("loan_type", ["loan", "advance", "fine"]);

export const loanStatusEnum = pgEnum("loan_status", [
	"active",
	"settled",
	"written_off",
]);

export const loanInstallmentStatusEnum = pgEnum("loan_installment_status", [
	"pending",
	"deducted",
	"skipped",
]);

export const reimbursementTypeEnum = pgEnum("reimbursement_type", [
	"expense",
	"leave_encash",
	"bonus_encash",
]);

export const reimbursementStatusEnum = pgEnum("reimbursement_status", [
	"requested",
	"approved",
	"rejected",
	"paid",
]);

export const payrollIssueTypeEnum = pgEnum("payroll_issue_type", [
	"blocker",
	"warning",
]);

export const payrollIssueStatusEnum = pgEnum("payroll_issue_status", [
	"open",
	"acknowledged",
	"resolved",
	"overridden",
]);

export const payPeriodStatusEnum = pgEnum("pay_period_status", [
	"open",
	"processing",
	"closed",
]);

// ─── Tables ──────────────────────────────────────────

export const countryPayrollProfile = pgTable(
	"country_payroll_profile",
	{
		id: cuid(),
		organizationId: orgRef(),
		countryCode: text("country_code").notNull(),
		countryName: text("country_name").notNull(),
		currency: text("currency").notNull(),
		effectiveYear: integer("effective_year").notNull(),
		taxBrackets: jsonb("tax_brackets").notNull(),
		personalAllowanceFormula: text("personal_allowance_formula")
			.default("standard")
			.notNull(),
		personalAllowanceThreshold: numeric("personal_allowance_threshold", {
			precision: 12,
			scale: 2,
		}),
		childAllowancePerChild: numeric("child_allowance_per_child", {
			precision: 12,
			scale: 2,
		}),
		overtimeAllowanceCap: numeric("overtime_allowance_cap", {
			precision: 12,
			scale: 2,
		}),
		insurancePremiumCapFormula: text("insurance_premium_cap_formula"),
		insurancePremiumCapAmount: numeric("insurance_premium_cap_amount", {
			precision: 12,
			scale: 2,
		}),
		employeeNISRate: numeric("employee_nis_rate", {
			precision: 5,
			scale: 2,
		}).notNull(),
		employerNISRate: numeric("employer_nis_rate", {
			precision: 5,
			scale: 2,
		}).notNull(),
		nisMaxEarnings: numeric("nis_max_earnings", { precision: 12, scale: 2 }),
		otherStatutoryRules: jsonb("other_statutory_rules"),
		isActive: boolean("is_active").default(true).notNull(),
		...timestamps,
	},
	(t) => [
		unique("cpp_org_country_year_uq").on(
			t.organizationId,
			t.countryCode,
			t.effectiveYear
		),
		index("cpp_org_idx").on(t.organizationId),
		index("cpp_country_year_idx").on(t.countryCode, t.effectiveYear),
	]
);

export const payrollSetting = pgTable(
	"payroll_setting",
	{
		id: cuid(),
		organizationId: orgRef(),
		defaultCurrency: text("default_currency").default("GYD").notNull(),
		defaultPayFrequency: text("default_pay_frequency")
			.default("monthly")
			.notNull(),
		weekdayOvertimeMultiplier: numeric("weekday_overtime_multiplier", {
			precision: 3,
			scale: 2,
		})
			.default("1.50")
			.notNull(),
		saturdayMultiplier: numeric("saturday_multiplier", {
			precision: 3,
			scale: 2,
		})
			.default("1.50")
			.notNull(),
		sundayMultiplier: numeric("sunday_multiplier", { precision: 3, scale: 2 })
			.default("2.00")
			.notNull(),
		publicHolidayMultiplier: numeric("public_holiday_multiplier", {
			precision: 3,
			scale: 2,
		})
			.default("2.00")
			.notNull(),
		nightShiftMultiplier: numeric("night_shift_multiplier", {
			precision: 3,
			scale: 2,
		})
			.default("1.00")
			.notNull(),
		workDays: jsonb("work_days").default([1, 2, 3, 4, 5]).notNull(),
		standardHoursPerDay: numeric("standard_hours_per_day", {
			precision: 4,
			scale: 2,
		})
			.default("8.00")
			.notNull(),
		lunchDeductionMinutes: integer("lunch_deduction_minutes")
			.default(0)
			.notNull(),
		minimumNetPayThreshold: numeric("minimum_net_pay_threshold", {
			precision: 12,
			scale: 2,
		}),
		paidHolidaysForHourly: boolean("paid_holidays_for_hourly")
			.default(true)
			.notNull(),
		autoGenerateEnabled: boolean("auto_generate_enabled")
			.default(false)
			.notNull(),
		autoGenerateDay: integer("auto_generate_day"),
		setupChecklistCompleted: jsonb("setup_checklist_completed")
			.default({})
			.notNull(),
		...timestamps,
	},
	(t) => [unique("payroll_setting_org_uq").on(t.organizationId)]
);

export const payPeriod = pgTable(
	"pay_period",
	{
		id: cuid(),
		organizationId: orgRef(),
		name: text("name").notNull(),
		startDate: date("start_date", { mode: "date" }).notNull(),
		endDate: date("end_date", { mode: "date" }).notNull(),
		payDate: date("pay_date", { mode: "date" }),
		frequency: text("frequency").notNull(),
		workingDays: integer("working_days").notNull(),
		expectedHours: numeric("expected_hours", {
			precision: 8,
			scale: 2,
		}).notNull(),
		status: payPeriodStatusEnum("status").default("open").notNull(),
		...timestamps,
	},
	(t) => [
		unique("pay_period_org_dates_uq").on(
			t.organizationId,
			t.startDate,
			t.endDate
		),
		index("pay_period_org_status_idx").on(t.organizationId, t.status),
		index("pay_period_org_start_idx").on(t.organizationId, t.startDate),
	]
);

export const payItem = pgTable(
	"pay_item",
	{
		id: cuid(),
		organizationId: orgRef(),
		type: payItemTypeEnum("type").notNull(),
		category: text("category").default("custom").notNull(),
		title: text("title").notNull(),
		description: text("description"),
		isFixed: boolean("is_fixed").default(true).notNull(),
		fixedAmount: numeric("fixed_amount", { precision: 12, scale: 2 }),
		basedOn: text("based_on"),
		rate: numeric("rate", { precision: 5, scale: 2 }),
		isTaxable: boolean("is_taxable").default(true).notNull(),
		isPreTax: boolean("is_pre_tax").default(false).notNull(),
		isTax: boolean("is_tax").default(false).notNull(),
		isStatutory: boolean("is_statutory").default(false).notNull(),
		employerRate: numeric("employer_rate", { precision: 5, scale: 2 }),
		includeAllActive: boolean("include_all_active").default(true).notNull(),
		isConditionBased: boolean("is_condition_based").default(false).notNull(),
		conditions: jsonb("conditions"),
		oneTimeDate: date("one_time_date", { mode: "date" }),
		hasMaxLimit: boolean("has_max_limit").default(false).notNull(),
		maxAmount: numeric("max_amount", { precision: 12, scale: 2 }),
		sortOrder: integer("sort_order").default(0).notNull(),
		isActive: boolean("is_active").default(true).notNull(),
		...timestamps,
	},
	(t) => [
		index("pay_item_org_type_idx").on(t.organizationId, t.type),
		index("pay_item_org_active_idx").on(t.organizationId, t.isActive),
	]
);

export const payItemAssignment = pgTable(
	"pay_item_assignment",
	{
		id: cuid(),
		payItemId: text("pay_item_id")
			.notNull()
			.references(() => payItem.id, { onDelete: "cascade" }),
		employeeId: text("employee_id").references(() => employeeProfile.id, {
			onDelete: "restrict",
		}),
		departmentId: text("department_id").references(() => department.id, {
			onDelete: "restrict",
		}),
		isExcluded: boolean("is_excluded").default(false).notNull(),
		overrideAmount: numeric("override_amount", { precision: 12, scale: 2 }),
		...timestamps,
	},
	(t) => [
		index("pay_item_assignment_item_idx").on(t.payItemId),
		index("pay_item_assignment_emp_idx").on(t.employeeId),
		index("pay_item_assignment_dept_idx").on(t.departmentId),
	]
);

export const payrollRun = pgTable(
	"payroll_run",
	{
		id: cuid(),
		organizationId: orgRef(),
		payPeriodId: text("pay_period_id")
			.notNull()
			.references(() => payPeriod.id, { onDelete: "restrict" }),
		batchName: text("batch_name").notNull(),
		status: payrollRunStatusEnum("status").default("draft").notNull(),
		employeeCount: integer("employee_count").default(0).notNull(),
		totalGross: numeric("total_gross", { precision: 14, scale: 2 })
			.default("0")
			.notNull(),
		totalDeductions: numeric("total_deductions", { precision: 14, scale: 2 })
			.default("0")
			.notNull(),
		totalNet: numeric("total_net", { precision: 14, scale: 2 })
			.default("0")
			.notNull(),
		totalEmployerContributions: numeric("total_employer_contributions", {
			precision: 14,
			scale: 2,
		})
			.default("0")
			.notNull(),
		currency: text("currency").notNull(),
		blockerCount: integer("blocker_count").default(0).notNull(),
		warningCount: integer("warning_count").default(0).notNull(),
		overrides: jsonb("overrides"),
		confirmedAt: timestamp("confirmed_at"),
		confirmedBy: text("confirmed_by").references(() => user.id, {
			onDelete: "set null",
		}),
		paidAt: timestamp("paid_at"),
		paidBy: text("paid_by").references(() => user.id, {
			onDelete: "set null",
		}),
		reversedAt: timestamp("reversed_at"),
		reversedBy: text("reversed_by").references(() => user.id, {
			onDelete: "set null",
		}),
		reversalReason: text("reversal_reason"),
		countryProfileId: text("country_profile_id").references(
			() => countryPayrollProfile.id,
			{ onDelete: "set null" }
		),
		generatedBy: text("generated_by")
			.notNull()
			.references(() => user.id, { onDelete: "restrict" }),
		...timestamps,
	},
	(t) => [
		unique("payroll_run_org_period_batch_uq").on(
			t.organizationId,
			t.payPeriodId,
			t.batchName
		),
		index("payroll_run_org_status_idx").on(t.organizationId, t.status),
		index("payroll_run_period_idx").on(t.payPeriodId),
	]
);

export const payslip = pgTable(
	"payslip",
	{
		id: cuid(),
		organizationId: orgRef(),
		payrollRunId: text("payroll_run_id")
			.notNull()
			.references(() => payrollRun.id, { onDelete: "restrict" }),
		employeeId: text("employee_id")
			.notNull()
			.references(() => employeeProfile.id, { onDelete: "restrict" }),
		contractId: text("contract_id")
			.notNull()
			.references(() => contract.id, { onDelete: "restrict" }),
		periodStart: date("period_start", { mode: "date" }).notNull(),
		periodEnd: date("period_end", { mode: "date" }).notNull(),
		currency: text("currency").notNull(),
		contractWage: numeric("contract_wage", {
			precision: 12,
			scale: 2,
		}).notNull(),
		wageType: text("wage_type").notNull(),
		basicPay: numeric("basic_pay", { precision: 12, scale: 2 }).notNull(),
		grossPay: numeric("gross_pay", { precision: 12, scale: 2 }).notNull(),
		taxableGross: numeric("taxable_gross", {
			precision: 12,
			scale: 2,
		}).notNull(),
		totalDeductions: numeric("total_deductions", {
			precision: 12,
			scale: 2,
		}).notNull(),
		netPay: numeric("net_pay", { precision: 12, scale: 2 }).notNull(),
		totalEmployerContributions: numeric("total_employer_contributions", {
			precision: 12,
			scale: 2,
		})
			.default("0")
			.notNull(),
		workedDays: numeric("worked_days", { precision: 6, scale: 2 }).notNull(),
		workedHours: numeric("worked_hours", { precision: 8, scale: 2 }).notNull(),
		overtimeHours: numeric("overtime_hours", { precision: 8, scale: 2 })
			.default("0")
			.notNull(),
		paidLeaveDays: numeric("paid_leave_days", { precision: 6, scale: 2 })
			.default("0")
			.notNull(),
		unpaidLeaveDays: numeric("unpaid_leave_days", { precision: 6, scale: 2 })
			.default("0")
			.notNull(),
		holidayDays: integer("holiday_days").default(0).notNull(),
		status: payslipStatusEnum("status").default("draft").notNull(),
		isReversed: boolean("is_reversed").default(false).notNull(),
		reversalOfId: text("reversal_of_id"),
		explanation: jsonb("explanation"),
		blockers: jsonb("blockers"),
		warnings: jsonb("warnings"),
		sentToEmployee: boolean("sent_to_employee").default(false).notNull(),
		generatedAt: timestamp("generated_at").defaultNow().notNull(),
		...timestamps,
	},
	(t) => [
		unique("payslip_emp_period_run_uq").on(
			t.employeeId,
			t.periodStart,
			t.periodEnd,
			t.payrollRunId
		),
		index("payslip_org_status_idx").on(t.organizationId, t.status),
		index("payslip_employee_idx").on(t.employeeId),
		index("payslip_run_idx").on(t.payrollRunId),
		index("payslip_period_idx").on(t.periodStart, t.periodEnd),
	]
);

export const payslipLineItem = pgTable(
	"payslip_line_item",
	{
		id: cuid(),
		payslipId: text("payslip_id")
			.notNull()
			.references(() => payslip.id, { onDelete: "cascade" }),
		payItemId: text("pay_item_id").references(() => payItem.id, {
			onDelete: "set null",
		}),
		type: payslipLineTypeEnum("type").notNull(),
		category: text("category").notNull(),
		title: text("title").notNull(),
		amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
		isEmployerContribution: boolean("is_employer_contribution")
			.default(false)
			.notNull(),
		isTaxable: boolean("is_taxable").default(false).notNull(),
		explanation: text("explanation"),
		sortOrder: integer("sort_order").default(0).notNull(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
	},
	(t) => [
		index("payslip_li_payslip_idx").on(t.payslipId),
		index("payslip_li_payitem_idx").on(t.payItemId),
		index("payslip_li_type_idx").on(t.type),
	]
);

export const payrollIssue = pgTable(
	"payroll_issue",
	{
		id: cuid(),
		organizationId: orgRef(),
		payrollRunId: text("payroll_run_id").references(() => payrollRun.id, {
			onDelete: "cascade",
		}),
		employeeId: text("employee_id")
			.notNull()
			.references(() => employeeProfile.id, { onDelete: "restrict" }),
		issueType: payrollIssueTypeEnum("issue_type").notNull(),
		code: text("code").notNull(),
		message: text("message").notNull(),
		resolution: text("resolution"),
		status: payrollIssueStatusEnum("status").default("open").notNull(),
		metadata: jsonb("metadata"),
		resolvedAt: timestamp("resolved_at"),
		resolvedBy: text("resolved_by").references(() => user.id, {
			onDelete: "set null",
		}),
		overriddenBy: text("overridden_by").references(() => user.id, {
			onDelete: "set null",
		}),
		overrideReason: text("override_reason"),
		...timestamps,
	},
	(t) => [
		index("payroll_issue_run_idx").on(t.payrollRunId, t.issueType),
		index("payroll_issue_emp_idx").on(t.employeeId),
		index("payroll_issue_status_idx").on(t.status),
	]
);

export const loan = pgTable(
	"loan",
	{
		id: cuid(),
		organizationId: orgRef(),
		employeeId: text("employee_id")
			.notNull()
			.references(() => employeeProfile.id, { onDelete: "restrict" }),
		type: loanTypeEnum("type").notNull(),
		title: text("title").notNull(),
		amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
		currency: text("currency").notNull(),
		providedDate: date("provided_date", { mode: "date" }).notNull(),
		totalInstallments: integer("total_installments").notNull(),
		installmentAmount: numeric("installment_amount", {
			precision: 12,
			scale: 2,
		}).notNull(),
		installmentStartDate: date("installment_start_date", {
			mode: "date",
		}).notNull(),
		paidInstallments: integer("paid_installments").default(0).notNull(),
		remainingBalance: numeric("remaining_balance", {
			precision: 12,
			scale: 2,
		}).notNull(),
		status: loanStatusEnum("status").default("active").notNull(),
		settledAt: timestamp("settled_at"),
		description: text("description"),
		approvedBy: text("approved_by").references(() => user.id, {
			onDelete: "set null",
		}),
		...timestamps,
	},
	(t) => [
		index("loan_org_idx").on(t.organizationId),
		index("loan_emp_status_idx").on(t.employeeId, t.status),
	]
);

export const loanInstallment = pgTable(
	"loan_installment",
	{
		id: cuid(),
		loanId: text("loan_id")
			.notNull()
			.references(() => loan.id, { onDelete: "cascade" }),
		sequenceNumber: integer("sequence_number").notNull(),
		dueDate: date("due_date", { mode: "date" }).notNull(),
		amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
		status: loanInstallmentStatusEnum("status").default("pending").notNull(),
		payslipId: text("payslip_id").references(() => payslip.id, {
			onDelete: "set null",
		}),
		paidAt: timestamp("paid_at"),
		createdAt: timestamp("created_at").defaultNow().notNull(),
	},
	(t) => [
		unique("loan_installment_seq_uq").on(t.loanId, t.sequenceNumber),
		index("loan_installment_loan_idx").on(t.loanId),
		index("loan_installment_payslip_idx").on(t.payslipId),
	]
);

export const reimbursement = pgTable(
	"reimbursement",
	{
		id: cuid(),
		organizationId: orgRef(),
		employeeId: text("employee_id")
			.notNull()
			.references(() => employeeProfile.id, { onDelete: "restrict" }),
		type: reimbursementTypeEnum("type").notNull(),
		title: text("title").notNull(),
		amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
		currency: text("currency").notNull(),
		reimbursementDate: date("reimbursement_date", { mode: "date" }).notNull(),
		attachmentUrl: text("attachment_url"),
		status: reimbursementStatusEnum("status").default("requested").notNull(),
		approvedBy: text("approved_by").references(() => user.id, {
			onDelete: "set null",
		}),
		approvedAt: timestamp("approved_at"),
		payslipId: text("payslip_id").references(() => payslip.id, {
			onDelete: "set null",
		}),
		description: text("description"),
		...timestamps,
	},
	(t) => [
		index("reimbursement_org_status_idx").on(t.organizationId, t.status),
		index("reimbursement_emp_idx").on(t.employeeId),
	]
);

// ─── Relations ───────────────────────────────────────

export const countryPayrollProfileRelations = relations(
	countryPayrollProfile,
	({ many }) => ({
		payrollRuns: many(payrollRun),
	})
);

export const payPeriodRelations = relations(payPeriod, ({ many }) => ({
	payrollRuns: many(payrollRun),
}));

export const payItemRelations = relations(payItem, ({ many }) => ({
	assignments: many(payItemAssignment),
	lineItems: many(payslipLineItem),
}));

export const payItemAssignmentRelations = relations(
	payItemAssignment,
	({ one }) => ({
		payItem: one(payItem, {
			fields: [payItemAssignment.payItemId],
			references: [payItem.id],
		}),
		employee: one(employeeProfile, {
			fields: [payItemAssignment.employeeId],
			references: [employeeProfile.id],
		}),
		department: one(department, {
			fields: [payItemAssignment.departmentId],
			references: [department.id],
		}),
	})
);

export const payrollRunRelations = relations(payrollRun, ({ one, many }) => ({
	payPeriod: one(payPeriod, {
		fields: [payrollRun.payPeriodId],
		references: [payPeriod.id],
	}),
	countryProfile: one(countryPayrollProfile, {
		fields: [payrollRun.countryProfileId],
		references: [countryPayrollProfile.id],
	}),
	payslips: many(payslip),
	issues: many(payrollIssue),
}));

export const payslipRelations = relations(payslip, ({ one, many }) => ({
	payrollRun: one(payrollRun, {
		fields: [payslip.payrollRunId],
		references: [payrollRun.id],
	}),
	employee: one(employeeProfile, {
		fields: [payslip.employeeId],
		references: [employeeProfile.id],
	}),
	contract: one(contract, {
		fields: [payslip.contractId],
		references: [contract.id],
	}),
	lineItems: many(payslipLineItem),
	loanInstallments: many(loanInstallment),
	reimbursements: many(reimbursement),
}));

export const payslipLineItemRelations = relations(
	payslipLineItem,
	({ one }) => ({
		payslip: one(payslip, {
			fields: [payslipLineItem.payslipId],
			references: [payslip.id],
		}),
		payItem: one(payItem, {
			fields: [payslipLineItem.payItemId],
			references: [payItem.id],
		}),
	})
);

export const payrollIssueRelations = relations(payrollIssue, ({ one }) => ({
	payrollRun: one(payrollRun, {
		fields: [payrollIssue.payrollRunId],
		references: [payrollRun.id],
	}),
	employee: one(employeeProfile, {
		fields: [payrollIssue.employeeId],
		references: [employeeProfile.id],
	}),
}));

export const loanRelations = relations(loan, ({ one, many }) => ({
	employee: one(employeeProfile, {
		fields: [loan.employeeId],
		references: [employeeProfile.id],
	}),
	installments: many(loanInstallment),
}));

export const loanInstallmentRelations = relations(
	loanInstallment,
	({ one }) => ({
		loan: one(loan, {
			fields: [loanInstallment.loanId],
			references: [loan.id],
		}),
		payslip: one(payslip, {
			fields: [loanInstallment.payslipId],
			references: [payslip.id],
		}),
	})
);

export const reimbursementRelations = relations(reimbursement, ({ one }) => ({
	employee: one(employeeProfile, {
		fields: [reimbursement.employeeId],
		references: [employeeProfile.id],
	}),
	payslip: one(payslip, {
		fields: [reimbursement.payslipId],
		references: [payslip.id],
	}),
}));

// ── Payment batch & export ──────────────────────────────

export const paymentBatchStatusEnum = pgEnum("payment_batch_status", [
	"draft",
	"reviewed",
	"exported",
	"submitted",
	"paid",
	"partially_paid",
	"failed",
	"cancelled",
]);

export const paymentItemStatusEnum = pgEnum("payment_item_status", [
	"pending",
	"exported",
	"submitted",
	"paid",
	"failed",
	"skipped",
]);

export const payrollPaymentBatch = pgTable(
	"payroll_payment_batch",
	{
		id: cuid(),
		organizationId: orgRef(),
		payrollRunId: text("payroll_run_id")
			.notNull()
			.references(() => payrollRun.id, { onDelete: "restrict" }),
		payPeriodId: text("pay_period_id")
			.notNull()
			.references(() => payPeriod.id, { onDelete: "restrict" }),
		status: paymentBatchStatusEnum("status").default("draft").notNull(),
		totalEmployees: integer("total_employees").default(0).notNull(),
		totalAmount: numeric("total_amount", { precision: 14, scale: 2 })
			.default("0")
			.notNull(),
		currency: text("currency").notNull(),
		exportFormat: text("export_format").default("csv").notNull(),
		createdBy: text("created_by")
			.notNull()
			.references(() => user.id, { onDelete: "restrict" }),
		exportedBy: text("exported_by").references(() => user.id, {
			onDelete: "set null",
		}),
		exportedAt: timestamp("exported_at"),
		submittedBy: text("submitted_by").references(() => user.id, {
			onDelete: "set null",
		}),
		submittedAt: timestamp("submitted_at"),
		markedPaidBy: text("marked_paid_by").references(() => user.id, {
			onDelete: "set null",
		}),
		markedPaidAt: timestamp("marked_paid_at"),
		failureReason: text("failure_reason"),
		...timestamps,
	},
	(t) => [
		index("payment_batch_org_idx").on(t.organizationId),
		index("payment_batch_run_idx").on(t.payrollRunId),
		index("payment_batch_status_idx").on(t.organizationId, t.status),
	]
);

export const payrollPaymentItem = pgTable(
	"payroll_payment_item",
	{
		id: cuid(),
		organizationId: orgRef(),
		paymentBatchId: text("payment_batch_id")
			.notNull()
			.references(() => payrollPaymentBatch.id, { onDelete: "cascade" }),
		payslipId: text("payslip_id")
			.notNull()
			.references(() => payslip.id, { onDelete: "restrict" }),
		employeeId: text("employee_id")
			.notNull()
			.references(() => employeeProfile.id, { onDelete: "restrict" }),
		employeeName: text("employee_name").notNull(),
		bankName: text("bank_name"),
		branchCode: text("branch_code"),
		accountNumberMasked: text("account_number_masked"),
		accountHolderName: text("account_holder_name"),
		amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
		currency: text("currency").notNull(),
		paymentReference: text("payment_reference"),
		status: paymentItemStatusEnum("status").default("pending").notNull(),
		failureReason: text("failure_reason"),
		...timestamps,
	},
	(t) => [
		index("payment_item_batch_idx").on(t.paymentBatchId),
		index("payment_item_emp_idx").on(t.employeeId),
		index("payment_item_status_idx").on(t.paymentBatchId, t.status),
	]
);

export const payrollPaymentBatchRelations = relations(
	payrollPaymentBatch,
	({ one, many }) => ({
		payrollRun: one(payrollRun, {
			fields: [payrollPaymentBatch.payrollRunId],
			references: [payrollRun.id],
		}),
		payPeriod: one(payPeriod, {
			fields: [payrollPaymentBatch.payPeriodId],
			references: [payPeriod.id],
		}),
		items: many(payrollPaymentItem),
	})
);

export const payrollPaymentItemRelations = relations(
	payrollPaymentItem,
	({ one }) => ({
		batch: one(payrollPaymentBatch, {
			fields: [payrollPaymentItem.paymentBatchId],
			references: [payrollPaymentBatch.id],
		}),
		payslip: one(payslip, {
			fields: [payrollPaymentItem.payslipId],
			references: [payslip.id],
		}),
		employee: one(employeeProfile, {
			fields: [payrollPaymentItem.employeeId],
			references: [employeeProfile.id],
		}),
	})
);
